### ISSUE TITLE
If statement logic issue

### ISSUE THREAD

**Issue by MDAddario** [ISDementyev/Complementation-Test#1]
I've noticed you use a couple of these guys:

`if cTestInput[i][c] != (0 or 1):`

I assume that the English translation of the condition would be 

> if cTestInput[i][c] is neither 0 nor 1:

But that's not what the condition does. The `or` doesn't work that way. It should instead be

`if cTestInput[i][c] != 0 and cTestInput[i][c] != 1:`

Or, if the list of numbers to check starts to get longer

`if cTestInput[i][c] not in [0, 1]:`

**Comment by ISDementyev** [comment]
Ok, thank you!

**Comment by ISDementyev** [comment]
Closed issue; all statements in question should be fixed
